### ISSUE TITLE
Is IsolatedStorage and SharedPreferences secure?

### ISSUE THREAD

**Issue by Cheesebaron** [ChristianRuiz/MvvmCross-SecureStorage#1]
Last time I looked these two are not really secure. On the other platforms credentials get encrypted. When using these two mechanisms credentials and other data wanting to be secured are stored in plaintext.

So maybe add a disclaimer at least notifying devs about this.

**Comment by ChristianRuiz** [comment]
Thanks Tomasz, I've checked it and as you say, on Android you are able to read the preferences file if you have a device with root access and on Windows Phone the encryption is provided by the ProtectData class but can be compromised also. I've added a note on the README file.

**Comment by Cheesebaron** [comment]
Cool thanks!

I guess it would be possible to add some crypto but any way you do it you will hit a problem saving either a private key or shared secret safely on the device.

Also, just wanted to let you know that I've added you to my list of Mvx Plugins here: https://github.com/Cheesebaron/Cheesebaron.MvxPlugins#other-mvvmcross-plugins

**Comment by ChristianRuiz** [comment]
Perfect, thanks!
